GET https://localhost:7273/api/todos



###
POST https://localhost:7273/api/todos 
Content-Type: application/json

{
  "title": "test"
}

###
PUT https://localhost:7273/api/todos/13 
Content-Type: application/json

{
  "id": 13,
  "isactive": true
}

###
DELETE https://localhost:7273/api/todos/3